### ISSUE TITLE
Tapping "Paypal check out" crashes the app on android

### ISSUE THREAD

**Issue by qmegas** [kraffslol/react-native-braintree-xplat#45]
```
FATAL EXCEPTION: main
	Process: com.test, PID: 1861
	java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1706816330, result=3, data=Intent { (has extras) }} to activity {com.test/com.test.MainActivity}: java.lang.RuntimeException: Cannot convert argument of type class com.braintreepayments.api.exceptions.UnexpectedException
		at android.app.ActivityThread.deliverResults(ActivityThread.java:4925)
		at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968)
		at android.app.ActivityThread.access$1600(ActivityThread.java:222)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:158)
		at android.app.ActivityThread.main(ActivityThread.java:7229)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
	 Caused by: java.lang.RuntimeException: Cannot convert argument of type class com.braintreepayments.api.exceptions.UnexpectedException
		at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:57)
		at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:36)
		at com.pw.droplet.braintree.Braintree.onActivityResult(Braintree.java:131)
		at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:265)
		at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:675)
		at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
		at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
		at android.app.Activity.dispatchActivityResult(Activity.java:7137)
		at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
		at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968) 
		at android.app.ActivityThread.access$1600(ActivityThread.java:222) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849) 
		at android.os.Handler.dispatchMessage(Handler.java:102) 
		at android.os.Looper.loop(Looper.java:158) 
		at android.app.ActivityThread.main(ActivityThread.java:7229) 
		at java.lang.reflect.Method.invoke(Native Method) 
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by qmegas** [comment]
Found solution.
In order to use PayPal in `AndroidManifest.xml` following lines should be added:
```xml
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
    android:launchMode="singleTask">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="${applicationId}.braintree" />
    </intent-filter>
</activity>
```
I think it should be mentioned in installation description.
